# Generated by Django 3.2.5 on 2021-07-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracks',
            old_name='track_name',
            new_name='name',
        ),
    ]
