# Generated by Django 3.2.5 on 2021-07-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20210723_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='explicit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tracks',
            name='track_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tracks',
            name='track_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
